
exec-once = awww-daemon
exec-once = waybar
exec-once = mako

source=config/env.conf
source=config/monitor.conf
source=config/input.conf
source=config/bindings.conf

general {
    gaps_in = 5

    gaps_out = 12

    border_size = 2

    col.active_border   = rgba(cba6f7ff) rgba(89b4faff) 45deg
    col.inactive_border = rgba(313244aa)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 0.93
    fullscreen_opacity = 1.0

    shadow {
        enabled = true
        range = 20
        render_power = 4
        color        = rgba(0000001a)
        color_inactive = rgba(00000000)    
    }

    blur {
        enabled          = true
        size             = 8
        passes           = 3
        noise            = 0.02
        contrast         = 1.0
        brightness       = 1.0
        vibrancy         = 0.2
        vibrancy_darkness = 0.5
        new_optimizations = true
        xray             = false
    }
}


animations {
    enabled = yes
 
    bezier = easeOutExpo,  0.16, 1,    0.3,  1
    bezier = easeOutQuart, 0.25, 1,    0.5,  1
    bezier = easeInOutBack,0.68,-0.55, 0.27, 1.55
    bezier = linear,       0,    0,    1,    1
    bezier = snap,         0.19, 1,    0.22, 1
 
    animation = windows,       1, 4,   easeOutExpo,   slide
    animation = windowsIn,     1, 4,   easeOutExpo,   popin 80%
    animation = windowsOut,    1, 3,   snap,          popin 80%
    animation = border,        1, 6,   easeOutQuart
    animation = borderangle,   1, 60,  linear,        loop
    animation = fade,          1, 4,   easeOutExpo
    animation = fadeIn,        1, 4,   easeOutExpo
    animation = fadeOut,       1, 3,   easeOutExpo
    animation = workspaces,    1, 5,   easeOutExpo,   slidefade 20%
    animation = workspacesIn,  1, 5,   easeOutExpo,   slidefade 20%
    animation = workspacesOut, 1, 4,   easeOutExpo,   slidefade 20%
    animation = layers,        1, 4,   easeOutExpo,   fade
    animation = layersIn,      1, 4,   easeOutExpo,   fade
    animation = layersOut,     1, 3,   easeOutExpo,   fade
    animation = specialWorkspace, 1, 5, easeOutExpo,  slidefadevert -20%
}


dwindle {
    preserve_split = true
    smart_split    = true
    smart_resizing = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo   = true
    animate_manual_resizes  = true
    animate_mouse_windowdragging = true
    enable_swallow          = true
    swallow_regex           = ^(kitty)$
    focus_on_activate       = true
}


# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

windowrule = suppress_event maximize, match:class .*

windowrule = no_focus on, match:class ^$, match:title ^$,match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = match:float 1, match:title ^(org.gnome.Nautilus)$

